pre-commit:
  parallel: true
  commands:
    check:
      run: bun check:fix
      stage_fixed: true
    # typecheck:
    #run: CI=true NX_TERMINAL_OUTPUT="static" NX_CLOUD_DISTRIBUTED_EXECUTION=false bun check-types
    encrypt-env:
      run: bun hide:env
      stage_fixed: true

    # test:
    #   run: CI=true NX_TERMINAL_OUTPUT="static" NX_CLOUD_DISTRIBUTED_EXECUTION=false bun test --passWithNoTests

pre-push:
  parallel: false
  commands:
    build:
      run: CI=true NX_TERMINAL_OUTPUT="static" NX_CLOUD_DISTRIBUTED_EXECUTION=false bun nx run-many -t build
    # test:
    #   run: CI=true NX_TERMINAL_OUTPUT="static" NX_CLOUD_DISTRIBUTED_EXECUTION=false bun test
    lint:
      run: CI=true NX_TERMINAL_OUTPUT="static" NX_CLOUD_DISTRIBUTED_EXECUTION=false bun check
