name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.21"

      - name: Setup Bun cache
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Generate Prisma client
        run: bun run db:generate:prod
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/test

      - name: Transform Prisma types
        run: bun --cwd packages/internal/prisma-defs run transform

      - name: Format and lint check
        run: bun run check

      - name: Build all packages
        run: bun build:all
        env:
          CI: true
          NX_TERMINAL_OUTPUT: static
          NX_CLOUD_DISTRIBUTED_EXECUTION: false

      - name: Type check
        run: bun run check-types
        env:
          CI: true
          NX_TERMINAL_OUTPUT: static
          NX_CLOUD_DISTRIBUTED_EXECUTION: false

      - name: Database migration check
        run: cd infrastructure/db && bun run migrate
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/test
          CI: true

      # - name: Run tests
      #   run: bun test:ci
      #   env:
      #     DATABASE_URL: postgresql://test:test@localhost:5432/test
      #     DOTENV_PRIVATE_KEY_DEV: ${{ secrets.DOTENV_PRIVATE_KEY_DEV }}
      #     DOTENV_PRIVATE_KEY_TEST: ${{ secrets.DOTENV_PRIVATE_KEY_TEST }}
      #     CI: true
      #     NX_TERMINAL_OUTPUT: static
      #     NX_CLOUD_DISTRIBUTED_EXECUTION: false
